### PR TITLE
Update background images using SVG

### LINKED ISSUE #24: Update icons to SVG
Currently the icons used for e.g. clear is bitmap images. Any reason not to use SVG background images these days?
https://caniuse.com/?search=background%20svg

https://github.com/seballot/spectrum/blob/master/src/spectrum.css#L43
https://github.com/seballot/spectrum/blob/master/src/spectrum.css#L531-L543

For example the clear icon looks blurry.
image

An example of using SVG as background image:
https://css-tricks.com/probably-dont-base64-svg/

Just a quick test using icon from https://icomoon.io/app/#/select and https://yoksel.github.io/url-encoder/ to generate CSS for background image with SVG.

image

```
background-image: url(data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1024 1024'%3E%3Cg%3E%3Cpath class='cursor-pointer' mi-d='M512 854q140 0 241-101t101-241q0-114-74-210l-478 478q96 74 210 74zM170 512q0 114 74 210l478-478q-96-74-210-74-140 0-241 101t-101 241zM512 86q176 0 301 125t125 301-125 301-301 125-301-125-125-301 125-301 301-125z' mi-fill='inherit' mi-stroke='inherit' mi-stroke-width='inherit' mi-stroke-linejoin='inherit' mi-stroke-linecap='inherit' mi-stroke-miterlimit='inherit' mi-opacity='1' ng-click='selectPath($index)' mi-absorb-clicks='' d='M512 854q140 0 241-101t101-241q0-114-74-210l-478 478q96 74 210 74zM170 512q0 114 74 210l478-478q-96-74-210-74-140 0-241 101t-101 241zM512 86q176 0 301 125t125 301-125 301-301 125-301-125-125-301 125-301 301-125z' fill='inherit' stroke='inherit' stroke-width='inherit' stroke-linejoin='inherit' stroke-linecap='inherit' stroke-miterlimit='inherit' opacity='1'%3E%3C/path%3E%3C/g%3E%3C/svg%3E);
```

### PR DESCRIPTION
**Pull request by bjarnef**
This PR fixes https://github.com/seballot/spectrum/issues/24 using SVG icons instead of the current bitmap images.
For now I have leaved the current images, but could probably be removed since SVG background image is well supported in modern browsers.

I noticed the checkered background is used two places for `.sp-colorize-container` and `.sp-preview, .sp-alpha, .sp-thumb-el` so maybe combine these classes.

I have used the checkmark and clear (do not distrub) from Material Icons on https://icomoon.io/app and https://yoksel.github.io/url-encoder/ to generate the background image.

### CODE REVIEW

**Comment by seballot** [comment]
Great thanks a lot !

Do we need to keep the old background-image attribute? is it working as a fallback?

**Comment by bjarnef** [comment]
Yea, currently it works as fallback, but it should probably only be a scenario in older browsers: https://caniuse.com/?search=svg%20background%20image

**Comment by bjarnef** [comment]
Btw. I noticed latest version on npm is 2.0.7 but here 2.0.5 is latest release https://github.com/seballot/spectrum/releases
It is listed in tags though https://github.com/seballot/spectrum/tags

**Comment by bjarnef** [comment]
Another minor thing I just noticed. The comment here should match the actual version number :)
https://github.com/seballot/spectrum/blob/master/src/spectrum.css#L2

**Comment by seballot** [comment]
Ok thanks ! it's merged and published with 2.0.8

**Comment by bjarnef** [comment]
It a bit confusing a version 2.0.22 exists on npm since this is the highest version. I guess this should have been version 2.0.2

image

**Pull request closed without merging**
